package com.ibtrader.risk.engine;

import com.ibtrader.domain.engine.EvaluationContext;
import com.ibtrader.domain.model.strategy.ValidatedTradeDecision;
import com.ibtrader.domain.port.inbound.RiskValidationPort;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Service responsible for validating trade decisions against defined risk limits.
 */
@Service
public class RiskEngine implements RiskValidationPort {

    /**
     * Validates the given trade decisions against the evaluation context and platform risk rules.
     *
     * @param decisions the list of validated trade decisions generated by the decision engine
     * @param context   the current evaluation context
     * @return a list of trade decisions that have passed risk validation (could be original, reduced, or filtered)
     */
    public List<ValidatedTradeDecision> validate(List<ValidatedTradeDecision> decisions, EvaluationContext context) {
        // Basic implementation for now - return as-is
        // In a real scenario, this would evaluate decisions against rules defined by LimitType
        return decisions;
    }
}
