-- ============================================================================
-- V20__create_trade_signals.sql
-- Trade signals generated by the decision engine.
-- ============================================================================

CREATE TABLE trade_signals
(
    id               UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    strategy_id      UUID          NOT NULL,
    symbol           VARCHAR(20)   NOT NULL,
    action           VARCHAR(10)   NOT NULL,
    quantity_type    VARCHAR(20)   NOT NULL,
    quantity_value   NUMERIC(18, 6) NOT NULL,
    reason           TEXT,
    confidence       FLOAT8        NOT NULL,
    generated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_trade_signals_strategy_id ON trade_signals (strategy_id);
