package com.ibtrader.domain.model.strategy;

import com.ibtrader.domain.model.common.Money;
import com.ibtrader.domain.model.order.OrderSide;
import lombok.Builder;
import lombok.Getter;
import lombok.ToString;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * Represents an executable order plan generated by the OrderPlanningEngine.
 * Contains the final validated symbol, side, absolute quantity, and execution policy 
 * (e.g. Market, Limit, TWAP, Iceberg) to be handed to the IBKR Outbox.
 */
@Getter
@Builder
@ToString
public class OrderPlan {
    private final UUID id;
    private final UUID decisionId;
    private final UUID strategyId;
    private final String symbol;
    private final OrderSide side;
    
    /** The absolute number of shares/contracts to trade. Evaluated from percentages/USD amounts. */
    private final BigDecimal targetQuantity;
    
    /** Optional limit price. Null for market orders. */
    private final Money limitPrice;
    
    /** The execution policy type (IMMEDIATE, TWAP, VWAP, ICEBERG) */
    private final String executionPolicy;
    
    /** JSON payload containing parameters for the execution policy (e.g. TWAP duration) */
    private final String policyParameters;
    
    private final Instant plannedAt;
}
