package com.ibtrader.domain.model.strategy;

/**
 * Represents the lifecycle status of an execution plan generated by a trading strategy.
 *
 * <p>An execution plan ({@code ExecutionPlan}) is created each time a strategy trigger fires
 * and carries a batch of orders to be submitted to IB. The {@code PlanStatus} tracks the
 * plan through its lifecycle from initial drafting to terminal completion, cancellation, or
 * failure.
 *
 * <p><b>Lifecycle overview:</b>
 * <pre>
 *   DRAFT ──► APPROVED ──► EXECUTING ──► COMPLETED   (terminal)
 *               │                    └──► FAILED      (terminal)
 *               └──────────────────────► CANCELLED    (terminal)
 * </pre>
 *
 * <p>A plan in {@link #DRAFT} has been generated but not yet reviewed or approved.
 * Depending on the platform configuration, approval may be automatic (immediate transition
 * to {@link #APPROVED}) or require manual confirmation from an operator.
 *
 * <pre>{@code
 * // Usage example
 * PlanStatus status = plan.getStatus();
 * if (status.isTerminal()) {
 *     archiveService.archivePlan(plan);
 * } else if (status.isActive()) {
 *     monitoringService.trackActivePlan(plan);
 * }
 * }</pre>
 *
 * @author IBTrader Platform
 * @version 1.0
 * @since 1.0
 */
public enum PlanStatus {

    /**
     * The execution plan has been generated but not yet approved for submission to IB.
     *
     * <p>In automated mode, plans transition from {@code DRAFT} to {@link #APPROVED}
     * immediately upon generation. In supervised mode, an operator must manually approve
     * the plan before orders are submitted.
     */
    DRAFT,

    /**
     * The execution plan has been approved and its orders are queued for submission to IB.
     *
     * <p>A plan in this state is considered active; the strategy coordinator will begin
     * submitting orders as soon as the trading session permits.
     */
    APPROVED,

    /**
     * Orders from this execution plan are currently being submitted to and/or filled by IB.
     *
     * <p>The plan remains in this state until all orders reach a terminal status
     * ({@code FILLED}, {@code CANCELLED}, {@code REJECTED}) or a timeout occurs.
     */
    EXECUTING,

    /**
     * All orders in this execution plan have reached a terminal state and the plan has
     * been fully processed. This is a terminal status — no further transitions will occur.
     *
     * <p>Note: {@code COMPLETED} does not necessarily imply that every order was filled;
     * it means the plan's lifecycle is finished and no more active orders remain.
     */
    COMPLETED,

    /**
     * The execution plan was cancelled before all orders were submitted or completed.
     * Cancellation may be initiated by an operator, by a risk limit breach, or by the
     * platform's safety checks. This is a terminal status.
     */
    CANCELLED,

    /**
     * The execution plan encountered an unrecoverable error during order submission or
     * execution (e.g., all orders rejected, IB connectivity lost). This is a terminal
     * status requiring manual investigation and remediation.
     */
    FAILED;

    // -------------------------------------------------------------------------
    // Helper Methods
    // -------------------------------------------------------------------------

    /**
     * Returns {@code true} if this plan status represents a terminal state — i.e., the
     * plan's lifecycle is complete and no further transitions are expected.
     *
     * <p>Terminal statuses: {@link #COMPLETED}, {@link #CANCELLED}, {@link #FAILED}.
     *
     * @return {@code true} if the plan has reached a terminal state; {@code false} otherwise
     */
    public boolean isTerminal() {
        return switch (this) {
            case COMPLETED, CANCELLED, FAILED -> true;
            default -> false;
        };
    }

    /**
     * Returns {@code true} if this plan status represents an actively-working plan that
     * has been approved and is either awaiting order submission or currently in the process
     * of being executed.
     *
     * <p>Active statuses: {@link #APPROVED}, {@link #EXECUTING}.
     *
     * @return {@code true} if the plan is currently active; {@code false} otherwise
     */
    public boolean isActive() {
        return switch (this) {
            case APPROVED, EXECUTING -> true;
            default -> false;
        };
    }
}
