package com.ibtrader.domain.port.outbound;

import com.ibtrader.domain.model.strategy.RebalancePlan;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Outbound port (repository) for {@link RebalancePlan} aggregate persistence.
 *
 * <p>Rebalance plans are generated by the strategy evaluation service and are
 * queried by the plan-execution orchestrator.  Support for latest-plan retrieval
 * allows callers to avoid re-running a plan that has already been generated for
 * the current evaluation cycle.</p>
 */
public interface RebalancePlanRepository {

    /**
     * Retrieves a rebalance plan by its domain UUID.
     *
     * @param id the domain UUID of the plan; must not be {@code null}
     * @return an {@link Optional} containing the plan if found, or
     *         {@link Optional#empty()} if no plan with that ID exists
     */
    Optional<RebalancePlan> findById(UUID id);

    /**
     * Retrieves all rebalance plans that belong to the specified strategy, ordered
     * from most recent to oldest.
     *
     * @param strategyId the domain UUID of the owning strategy; must not be {@code null}
     * @return a (possibly empty) list of rebalance plans; never {@code null}
     */
    List<RebalancePlan> findByStrategyId(UUID strategyId);

    /**
     * Retrieves the most recently generated rebalance plan for the specified strategy.
     *
     * <p>This is used to check whether a valid plan already exists before generating
     * a new one, avoiding unnecessary plan duplication.</p>
     *
     * @param strategyId the domain UUID of the strategy; must not be {@code null}
     * @return an {@link Optional} containing the latest plan if any exist, or
     *         {@link Optional#empty()} if no plans have been generated yet
     */
    Optional<RebalancePlan> findLatestByStrategyId(UUID strategyId);

    /**
     * Persists a new or updated {@link RebalancePlan} aggregate.
     *
     * @param plan the rebalance plan to persist; must not be {@code null}
     * @return the persisted plan, potentially with infrastructure-enriched fields
     */
    RebalancePlan save(RebalancePlan plan);
}
